package dandan.wendy.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentId
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentType
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Integer commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentator
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtCreate
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtModified
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likeCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    private Integer commentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentId
     *
     * @return the value of comment.parentId
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentId
     *
     * @param parentId the value for comment.parentId
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentType
     *
     * @return the value of comment.commentType
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentType
     *
     * @param commentType the value for comment.commentType
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentator
     *
     * @return the value of comment.commentator
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentator
     *
     * @param commentator the value for comment.commentator
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtCreate
     *
     * @return the value of comment.gmtCreate
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtCreate
     *
     * @param gmtCreate the value for comment.gmtCreate
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtModified
     *
     * @return the value of comment.gmtModified
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtModified
     *
     * @param gmtModified the value for comment.gmtModified
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likeCount
     *
     * @return the value of comment.likeCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likeCount
     *
     * @param likeCount the value for comment.likeCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentCount
     *
     * @return the value of comment.commentCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentCount
     *
     * @param commentCount the value for comment.commentCount
     *
     * @mbg.generated Wed Jul 15 15:27:37 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
}