package dandan.wendy.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifier
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outerId
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notiType
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Integer notiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.gmtCreate
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notiStatus
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private Integer notiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifierName
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outerTitle
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifier
     *
     * @return the value of notification.notifier
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifier
     *
     * @param notifier the value for notification.notifier
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver
     *
     * @return the value of notification.receiver
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver
     *
     * @param receiver the value for notification.receiver
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outerId
     *
     * @return the value of notification.outerId
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outerId
     *
     * @param outerId the value for notification.outerId
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notiType
     *
     * @return the value of notification.notiType
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Integer getNotiType() {
        return notiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notiType
     *
     * @param notiType the value for notification.notiType
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setNotiType(Integer notiType) {
        this.notiType = notiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.gmtCreate
     *
     * @return the value of notification.gmtCreate
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.gmtCreate
     *
     * @param gmtCreate the value for notification.gmtCreate
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notiStatus
     *
     * @return the value of notification.notiStatus
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public Integer getNotiStatus() {
        return notiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notiStatus
     *
     * @param notiStatus the value for notification.notiStatus
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setNotiStatus(Integer notiStatus) {
        this.notiStatus = notiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifierName
     *
     * @return the value of notification.notifierName
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifierName
     *
     * @param notifierName the value for notification.notifierName
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outerTitle
     *
     * @return the value of notification.outerTitle
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outerTitle
     *
     * @param outerTitle the value for notification.outerTitle
     *
     * @mbg.generated Fri Jul 17 17:33:38 CST 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}